name: Ko Build

on:
  workflow_call:
    inputs:
      folder:
        required: true
        type: string

jobs:
  build:
    name: Build Images
    runs-on: [self-hosted, Linux]
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - uses: actions/checkout@v3
      - uses: imjasonh/setup-ko@v0.6

      - name: Set tag prefix
        if: github.ref_name != 'main'
        run: |
          echo "TAG_PREFIX=${{ github.ref_name }}-" | tr '/' '-' >> $GITHUB_ENV

      - name: Set tag
        run: |
          echo "TAG=${{ env.TAG_PREFIX }}${GITHUB_SHA::7}" >> $GITHUB_ENV

      - working-directory: ./cmd/${{ inputs.folder }}
        run: ko publish --base-import-paths . -t ${{ env.TAG }}
        id: ko-publish

      - uses: 8BitJonny/gh-get-current-pr@2.1.3
        id: PR
        with:
          filterOutClosed: true
      - name: Comment
        if: steps.PR.outputs.number
        uses: peter-evans/create-or-update-comment@v2.1.0
        with:
          issue-number: ${{ steps.PR.outputs.number }}
          body: >
            @${{ github.triggering_actor }} Build complete, ${{ steps.ko-publish.outcome }}: 
            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

            Image: `ghcr.io/coreweave/dataset-downloader/${{ inputs.folder }}:${{ env.TAG }}`
